"""Phase E.1 event type constants."""

from __future__ import annotations

EVENT_PHASE_DETECTED = "SHOCK_DETECTED"
EVENT_PHASE_MONITORING = "MONITORING_REVERSAL"
EVENT_PHASE_OBSERVATION = "OBSERVATION"
EVENT_PHASE_REVERSAL_CANDIDATE = "REVERSAL_CANDIDATE"
EVENT_PHASE_REVERSAL_CONFIRMED = "REVERSAL_CONFIRMED"
EVENT_PHASE_PAPER_ENTRY = "PAPER_ENTRY"
EVENT_PHASE_MANAGING = "MANAGING_POSITION"
EVENT_PHASE_EXPIRED = "EXPIRED_NO_REVERSAL"
EVENT_PHASE_CLOSED = "CLOSED"

SHOCK_DIRECTION_UP = "UP"
SHOCK_DIRECTION_DOWN = "DOWN"

CLASSIFICATION_MARKET_WIDE = "MARKET_WIDE"
CLASSIFICATION_SECTOR_WIDE = "SECTOR_WIDE"
CLASSIFICATION_ASSET_SPECIFIC = "ASSET_SPECIFIC"
CLASSIFICATION_UNKNOWN = "UNKNOWN"

CONTEXT_TYPES = (
    "NEWS",
    "TELEGRAM_SIGNAL",
    "TRADER_THESIS",
    "MARKET_COMMENTARY",
    "WHALE_FLOW",
    "ONCHAIN_EVENT",
    "POLYMARKET_STATE",
)

DETECTOR_IDS = ("SHOCK_A", "SHOCK_B", "SHOCK_C", "SHOCK_D", "SHOCK_E")
REVERSAL_IDS = ("R1", "R2", "R3", "R4", "R5")
EXIT_IDS = ("EXIT_A", "EXIT_B", "EXIT_C", "EXIT_D", "EXIT_E")
