"""Phase E.2 instrument and classification type constants."""

from __future__ import annotations

# Asset classes
ASSET_CLASS_CRYPTO = "CRYPTO"
ASSET_CLASS_EQUITY = "EQUITY"
ASSET_CLASS_INDEX = "INDEX"
ASSET_CLASS_ETF = "ETF"
ASSET_CLASS_COMMODITY = "COMMODITY"

ASSET_CLASSES = (
    ASSET_CLASS_CRYPTO,
    ASSET_CLASS_EQUITY,
    ASSET_CLASS_INDEX,
    ASSET_CLASS_ETF,
    ASSET_CLASS_COMMODITY,
)

# Instrument types
INST_TYPE_SPOT = "SPOT"
INST_TYPE_PERPETUAL = "PERPETUAL"
INST_TYPE_TOKENIZED_SPOT = "TOKENIZED_SPOT"
INST_TYPE_TOKENIZED_EQUITY = "TOKENIZED_EQUITY"
INST_TYPE_TOKENIZED_ETF = "TOKENIZED_ETF"
INST_TYPE_SYNTHETIC_PERPETUAL = "SYNTHETIC_PERPETUAL"
INST_TYPE_OTHER = "OTHER"

# Trading hours modes
HOURS_CRYPTO_24H = "CRYPTO_24H"
HOURS_US_EQUITY = "US_EQUITY"
HOURS_COMMODITY = "COMMODITY_SESSION"

# Session regimes (Task D)
SESSION_CRYPTO_24H = "CRYPTO_24H"
SESSION_PREMARKET = "PREMARKET"
SESSION_US_REGULAR = "US_REGULAR"
SESSION_AFTER_HOURS = "AFTER_HOURS"
SESSION_UNDERLYING_CLOSED = "UNDERLYING_CLOSED"
SESSION_WEEKEND = "WEEKEND"
SESSION_MACRO_EVENT_WINDOW = "MACRO_EVENT_WINDOW"

# Cross-asset classifications (Task F) — configurable rules in cross_asset_classifier.py
CROSS_CRYPTO_MARKET_WIDE = "CRYPTO_MARKET_WIDE"
CROSS_EQUITY_MARKET_WIDE = "EQUITY_MARKET_WIDE"
CROSS_TECH_SECTOR_WIDE = "TECH_SECTOR_WIDE"
CROSS_MACRO_DRIVEN = "MACRO_DRIVEN"
CROSS_COMMODITY_GEOPOLITICAL = "COMMODITY_GEOPOLITICAL"
CROSS_ASSET_SPECIFIC = "ASSET_SPECIFIC"
CROSS_TOKENIZED_DISLOCATION = "TOKENIZED_MARKET_DISLOCATION"
CROSS_UNKNOWN = "UNKNOWN"

# Liquidity tiers
TIER_CORE = "CORE"
TIER_LIQUID = "LIQUID"
TIER_WATCH = "WATCH"
TIER_INACTIVE = "INACTIVE"

# Venues
VENUE_BINANCE_FUTURES = "binance_futures"
VENUE_BYBIT_LINEAR = "bybit_linear"
VENUE_BYBIT_SPOT = "bybit_spot"

# Candidate canonical assets for discovery (not enabled until API confirms)
CRYPTO_CANDIDATES = ("BTC", "ETH", "SOL", "XRP", "BNB", "DOGE", "LINK", "SUI", "ADA", "AVAX")
EQUITY_CANDIDATES = ("TSLA", "AAPL", "NVDA", "META", "AMZN", "MSFT", "GOOGL")
INDEX_CANDIDATES = ("SP500_PROXY", "NASDAQ100_PROXY")
COMMODITY_CANDIDATES = ("GOLD", "SILVER", "OIL")

# Bybit symbol → canonical mapping (only when discovered via API)
BYBIT_INDEX_MAP = {
    "US500USDT": "SP500_PROXY",
    "US100USDT": "NASDAQ100_PROXY",
}
BYBIT_COMMODITY_MAP = {
    "XAUUSDT": "GOLD",
    "XAGUSDT": "SILVER",
    "XAUTUSDT": "GOLD",
    "CLUSDT": "OIL",
}
